### PR TITLE
cleanups

### PR DESCRIPTION
**Pull request by jule64**
Some easy ones - just to warm up :)

### CODE REVIEW

**Comment by douggie** [comment]
Looks good to me, Tim, any comments?

**Comment by timolson** [comment]
Looks like we have some spaces vs tabs issues with the formatting.  I think I started the project with spaces-only.  Do you have an easy way to convert?

**Comment by jule64** [comment]
I'll look at it, I did press tab on many places but I assumed IntelliJ converted automatically :(

**Comment by timolson** [comment]
IDEA has space/tab preferences for the editor, but there is also a menu item under "Edit" to convert tabs to spaces or vice-versa for the current file.

**Comment by jule64** [comment]
Thanks Tim will look in a bit and send update. Sorry about that

**Comment by jule64** [comment]
Hi Tim,  actually my IDE was setup correctly for spaces so I think my commits are ok right?

Said that I can see a lot of files contain tabs (including some files I committed though the tabs seems to have been there from previous commits). Will clean those out and send commit though just want to check if I should do that with a new pull request?

**Comment by timolson** [comment]
See #83 for tabs/spaces cleanup

**Pull request merged**
