### PR TITLE
revert the hibernate version

### PR DESCRIPTION
**Pull request by edenpan**
Revert the hibernate version back to 5.2.18.

### CODE REVIEW

**Comment by timolson** [comment]
This version was bumped due to a high severity security vulnerability in Hibernate.  DO NOT DOWNGRADE to this version!  Hibernate 5.2.18 contains a vulnerability.  I must reject this PR.  The way to address your original error would be to fix the injection to work with the latest Hibernate version.

**Comment by timolson** [comment]
See #166

**Comment by douggie** [comment]
Do you have the error?

**Comment by douggie** [comment]
I just tested 5.3.27.Final seem ok.

**Comment by timolson** [comment]
#168

**Pull request closed without merging**
